### ISSUE TITLE
Strange behaviour of arguments in the OpenCL kernel function

### ISSUE THREAD

**Issue by Quirinms** [s-u/OpenCL#14]
The following code does work in R, but there is a seemingly strange behaviour.
The parameter in the OpenCL function named "count" is not used. But if I just remove it, the code stops working. It is even more strange, that there is no parameter passed for the argument "count". The code works correct (verified with default R functionality) with the argument count. But apparently the code doesnt work without it at all.

If the argument count is just removed, following error occurs:

Error in oclRun(kernel = KernelFun, size = Size, as.clBuffer(VectorizedInput,  : 
  failed to set second kernel argument as output length in clSetKernelArg

I assume, there must be a piece of information how to access the OpenCL kernel function correctly I am missing or there is an actual bug.

```
code = readLines("DistanceMatrix_OpenCL.cl")

KernelFun = withCallingHandlers({
  oclSimpleKernel(Context, "distance_matrix", code)
}, warning = function(condition) {
  txt = "OpenCL implementation does not support out-of-order execution"
  if(startsWith(conditionMessage(condition), txt)){
    invokeRestart("muffleWarning")
  }
})

N               = dim(Data)[1]
DIM           = dim(Data)[2]
Size            = N*N
VectorizedInput = as.vector(Data)
tmpDM           = as.numeric(oclRun(kernel = KernelFun,
                                    size   = Size,
                                    as.clBuffer(VectorizedInput, Context),
                                    N, DIM,
                                    dim    = c(N,N)))
matrix(tmpDM, nrow = N, ncol = N)
```

```
__kernel void distance_matrix(
  __global numeric* output,
  const unsigned int count,
  __global numeric* input,
  const int N,
  const int DIM){

  size_t i = get_global_id(0);
  size_t j = get_global_id(1);

  if(i < N && j < i){
    double tmpRes = 0;
    for(int k = 0; k < DIM; ++k){
      tmpRes = tmpRes + (input[i+k*N] - input[j+k*N]) * (input[i+k*N] - input[j+k*N]);
    }
    tmpRes = sqrt(tmpRes);
    output[j*N+i] = tmpRes;
    output[i*N+j] = tmpRes;
  }
}
```

**Comment by aaronpuchert** [comment]
Have a look at the [documentation](https://search.r-project.org/CRAN/refmans/OpenCL/html/oclRun.html) for `oclRun`, section "Details":

> The kernel is expected to have either `__global double *` or `__global float *` type (write-only) as the first argument which will be used for the result and `const unsigned int` second argument denoting the result length. All other arguments are assumed to be read-only and will be filled according to the `...` values.

The result size (the second argument to `oclRun`) is always passed as second parameter to the kernel. We don't know if the kernel needs it, and there is little cost in always passing it (as far as we know).
