### ISSUE TITLE
Cannot install OpenCL R package

### ISSUE THREAD

**Issue by strategist922** [s-u/OpenCL#2]
Hi,

   I try to install OpenCL R package in Windows 10 Enterprise X64 with Microsoft R Open 3.3.3 and RStudio.
May I know how to solve this issue?

Following are the error messages:
======================
> install.packages("OpenCL")
Installing package into ‘C:/Users/James Chang/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘OpenCL’
Do you want to attempt to install these from sources?
y/n: y
installing the source package ‘OpenCL’

trying URL 'https://mran.microsoft.com/snapshot/2017-03-15/src/contrib/OpenCL_0.1-3.tar.gz'
Content type 'application/octet-stream' length 15524 bytes (15 KB)
downloaded 15 KB

* installing *source* package 'OpenCL' ...
** package 'OpenCL' successfully unpacked and MD5 sums checked
** libs
c:/Rtools/mingw_64/bin/gcc -m64 -I"C:/PROGRA~1/MICROS~1/ROPEN~1/include" -DNDEBUG     -I"C:/swarm/workspace/External-R-3.3.3/vendor/extsoft/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c ocl.c -o ocl.o
ocl.c:6:23: fatal error: CL/opencl.h: No such file or directory
 #include <CL/opencl.h>
                       ^
compilation terminated.
make: *** [ocl.o] Error 1
Warning: 執行中命令 'make -f "Makevars" -f "C:/PROGRA~1/MICROS~1/ROPEN~1/etc/x64/Makeconf" -f "C:/PROGRA~1/MICROS~1/ROPEN~1/share/make/winshlib.mk" SHLIB="OpenCL.dll" WIN=64 TCLBIN=64 OBJECTS="ocl.o tools.o"' 已有狀態 2
ERROR: compilation failed for package 'OpenCL'
* removing 'C:/Users/James Chang/Documents/R/win-library/3.3/OpenCL'
Warning in install.packages :
  running command '"C:/PROGRA~1/MICROS~1/ROPEN~1/bin/x64/R" CMD INSTALL -l "C:\Users\James Chang\Documents\R\win-library\3.3" C:\Users\JAMESC~1\AppData\Local\Temp\RtmpItcCbm/downloaded_packages/OpenCL_0.1-3.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘OpenCL’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\James Chang\AppData\Local\Temp\RtmpItcCbm\downloaded_packages’
=========================
I already install Intel® SDK for OpenCL™ Applications for Windows* 2016 Version 6.3.0.1904
Following already setting im my system environment variable
INTELGTDEBUGGERROOT C:\Program Files (x86)\Intel\OpenCL SDK\6.3\igfxdbg\
INTELOCLPATH C:\Program Files (x86)\Intel\OpenCL SDK\6.3\bin\x64;C:\Program Files (x86)\Intel\OpenCL SDK\6.3\bin\x86
INTELOCLSDKROOT C:\Program Files (x86)\Intel\OpenCL SDK\6.3\

**Comment by aaronpuchert** [comment]
You'll need to tell the compiler where to find the header file `CL/opencl.h` and later where to find the library `libOpenCL.a`. I can't tell you where they are, but you probably find them in the Intel SDK.

Then change `src/Makevars` as follows
```make
PKG_CFLAGS=-I<directory containing CL/opencl.h>
PKG_LIBS=`if test -z "$${PKG_LIBS}"; then if uname|grep -i darwin >/dev/null; then echo '-framework OpenCL'; else echo '-lOpenCL'; fi; else echo "$${PKG_LIBS}"; fi` -L<directory containing libOpenCL.a>
```
in a local copy of the package and build from there.

However, last time I tried this on Windows, it still didn't work. You may need to apply [additional changes](https://github.com/s-u/OpenCL/compare/master...aaronpuchert:windows). Unfortunately, I don't have a Windows machine any longer, but I remember that this worked on Windows 7.

**Comment by s-u** [comment]
See `NEWS` on how to set necessary environment variables.

**Comment by MarkTeves** [comment]
I try it but the result seems.
Help me.

**Comment by s-u** [comment]
Do you have any details? You have to set `OCL` to point to your SDK and make sure you have the correct Rtools installed to build R packages. If you need any help, you have your exact invocation, settings and any errors you get.

**Comment by MarkTeves** [comment]
Thank you.
Rtool : Rtool43
error :
[image: image.png]
and [image: image.png]
