### ISSUE TITLE
Windows: install.packages("OpenCL") fail

### ISSUE THREAD

**Issue by Jacobzwj** [s-u/OpenCL#7]
- Windows 10 Pro
- Rstudio Version 1.3.1056; R version 3.6.3
- Nvidia GeForce RTX 2060 Super

Hi,
Thanks for your wonderful work on this package!
I tried to install the OpenCL package in Rstudio, but it failed with the following error messages:

#############################################
Installing package into ‘C:/Users/Administrator/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘OpenCL’
installing the source package ‘OpenCL’
trying URL 'https://cran.rstudio.com/src/contrib/OpenCL_0.2-2.tar.gz'
Content type 'application/x-gzip' length 20881 bytes (20 KB)
downloaded 20 KB
installing *source* package 'OpenCL' ...
** package 'OpenCL' successfully unpacked and MD5 sums checked
** using staged installation

**ERROR: OCL not set!
You will need a working OpenCL SDK with headers
and libraries for both i386 and x64
Set OCL to the root of the SDK
You can also set individial variables OCLINC,
OCL32LIB and OCL64LIB. If they are not set,
the default layout will be assumed.**
ERROR: configuration failed for package 'OpenCL'
removing 'C:/Users/Administrator/Documents/R/win-library/3.6/OpenCL'
Warning in install.packages :
  installation of package ‘OpenCL’ had non-zero exit status
###################################################

I think the error messages was clear as above. But I don't know how to solve "**You will need a working OpenCL SDK with headers
and libraries for both i386 and x64, Set OCL to the root of the SDK**".

I had installed NVIDIA driver/Cuda/NVIDIA GPU Computing SDK, and I found the path of: 
- "opencl.h" : "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4/include/CL"
- "OpenCL.lib": "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\lib\x64"

I read the "NEWS" as another issue posted, then I found that I cannot even understand how to do the following things:

> Windows configuration has been simplified. On Windows, you have to set the OCL environemnt variable to the root of the OpenCL SDK. By default the CPPFLAGS and LIBS will be constrcuted from that location depending on whether 32-bit or 64-bit binaries are produced by appending lib/x64/OpenCL.lib or lib/x86/OpenCL.lib respecitvely. Includes are assumed to be in the includes directory. All of the above can be overridden by setting OCLINC to the necessary pre-processor flags and OCL32LIB or OCL64LIB for 32-bit and 64-bit linker flags. (Note that OCL must still be set even if you override all flags).

Could you please explain more to me about : how to set OCL to the root of the SDK?
Looking forward to your reply, and many many thanks!

Best,
Jacob

**Comment by aaronpuchert** [comment]
This is talking about [environment variables](https://en.wikipedia.org/wiki/Environment_variable). I've looked a bit around Rstudio and can't find an option to set them. I don't run Windows anymore, but I think you have two or maybe three options:
* One is to set `OCL` persistently via GUI: open the System settings in the Control Center (or run `sysdm.cpl`) then under "Advanced" you'll find a button to change the environment variables. (For detailed steps, see e.g. [here](https://phoenixnap.com/kb/windows-set-environment-variable).)
* The other is to set `OCL` only for the installing the package. Open the command line (`cmd.exe`), run [set](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/set_1) and then run Rstudio from there.
* If I remember correctly, you can also set environment variables for a link file on your desktop, but that might be my imagination.

In the end, you'll have to set `OCL=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4`. I think that backslashes should work, but maybe it needs to be regular slashes.

**Comment by s-u** [comment]
@Qiegao1994 see R documentation on setting environment values. I don't have a Windows machine with CUDA, so cannot test, but if using R you can try

```r
Sys.setenv(OCL="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4")
```

Linking to shared libraries on Windows is a lot more complicated than other systems, so you need libraries that are compatible with MinGW which is what R is using.

Also if in doubt, please use R when installing packages as RStudio uses different environment and overrides `install.packages` and thus may not behave like R.

**Comment by s-u** [comment]
I assume I can close this assuming once you set `OCL`. Beware, though, there there is still potentially an issue with #6 if you use dynamic linking just in case you hit that one.

**Comment by Jacobzwj** [comment]
Thank you for your suggestion! I will try~

Simon Urbanek ***@***.***> 于2021年8月16日周一 上午5:42写道：

**Comment by Jacobzwj** [comment]
> This is talking about [environment variables](https://en.wikipedia.org/wiki/Environment_variable). I've looked a bit around Rstudio and can't find an option to set them. I don't run Windows anymore, but I think you have two or maybe three options:
> 
> * One is to set `OCL` persistently via GUI: open the System settings in the Control Center (or run `sysdm.cpl`) then under "Advanced" you'll find a button to change the environment variables. (For detailed steps, see e.g. [here](https://phoenixnap.com/kb/windows-set-environment-variable).)
> * The other is to set `OCL` only for the installing the package. Open the command line (`cmd.exe`), run [set](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/set_1) and then run Rstudio from there.
> * If I remember correctly, you can also set environment variables for a link file on your desktop, but that might be my imagination.
> 
> In the end, you'll have to set `OCL=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4`. I think that backslashes should work, but maybe it needs to be regular slashes.

I found that I could use the OpenCL function in a package named brms which solve my issues. Anyway, thank you for your advice about environment variables, I learned a lot!
